// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwnnixxbalyajssmvmzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3bm5peHhiYWx5YWpzc212bXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyOTQ2MjQsImV4cCI6MjA3Mjg3MDYyNH0.h-zohm_DvKN4UfmZj3y2YhhVpGSuTxCWL6wKbjWuCUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});